# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a6aadf15b3cb8cd27dfd0b1724c644202d12f81d464e92fa8b4da1569e933b14bb941b875a9b6c599327274cb5c365db7e509342b310fb5ea6f8518fb308e02f

test:
  secret_key_base: ada90a3443728d36cfdae215f0781e40429b5eeeaa5f6173ee5ea35e9fb0dcdcf9a421ee499024a8e30bbc1d772286b1d4854fde41e2beff7f091c01d7d2c88f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
